[package]
name = "linkd"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"
authors = [
  "xla <self@xla.is>",
]

autobins = false

[[bin]]
name = "linkd"
doctest = false
test = false

[dependencies.tokio]
version = "1.13.1"
default-features = false
features = [ "macros", "process", "rt-multi-thread" ]

[dependencies.linkd-lib]
path    = "../../cli/linkd-lib"
version = "0.1.0"

[dependencies.git-tempfile]
version = "1.0.6"
